image: docker:latest

services:
        - docker:dind

variables:
        DOCKER_DRIVER: overlay2

stages:
        - build
        - push
        - release

before_script:
        - docker info

build:
        stage: build
        script:
                - docker build -t $CI_REGISTRY_IMAGE:latest .
        only:
                - main

push_to_gitlab_registry:
        stage: push
        script:
                - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
                - docker push $CI_REGISTRY_IMAGE:latest
        only:
                - main
        dependencies:
                - build

release_to_docker_hub:
        stage: release
        script:
                - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
                - docker tag $CI_REGISTRY_IMAGE:latest $DOCKER_HUB_USERNAME/my-flask-app:latest
                - docker push $DOCKER_HUB_USERNAME/my-flask-app:latest
        only:
                - main
        dependecies:
                - build
