replicaCount: 2

image:
  repository: scelle/my-flask-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30001

ingress:
  host: my-flask-app.local

env:
  FLASK_ENV: "production"
  DATABASE_URL: "sqlite:///mydatabase.db"

secretKey: "mySecretKey"

