replicaCount: 2

image:
  repository: scelle/my-flask-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30001

ingress:
  enabled: true
  host: my-flask-app.local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /
  pathType: Prefix

env:
  FLASK_ENV: "production"
  DATABASE_URL: "sqlite:///mydatabase.db"

secretKey: "mySecretKey"

